"""
backend/import_satya_may2026.py
================================
Imports SATYA DISTRIBUTORS secondary sales report (May 2026) into the
SalesEntry table so that ROI calculations work automatically.

Source: SATYA DISTRIBUTORS Customer & Product Analysis 01/05/2026–31/05/2026
        generated by PROFITMAKER software (Daxinsoft Technologies, Hyd)

Usage:
    cd fortel-crm
    python -m backend.import_satya_may2026

How it works:
    1. For each customer in the report, match by phone number → doctor_id
    2. For each product, match by name (fuzzy) → product_id; auto-create if missing
    3. For each rep name, match to user → associate_id (fallback: None logged)
    4. Week is derived from invoice date (day 1-7=W1, 8-14=W2, 15-21=W3, 22+=W4)
    5. Inserts SalesEntry rows; skips duplicates (upserts quantity/value)

After running:
    - ROI screen will show actual May 2026 sales per doctor
    - Unmatched customers and reps are logged to satya_import_log.txt
"""

import os, sys, re
from datetime import datetime
from difflib import SequenceMatcher

# ── DB setup ─────────────────────────────────────────────────────────────────
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.database import SessionLocal
from backend.models.models import Doctor, User, Product, SalesEntry

db = SessionLocal()
YEAR, MONTH = 2026, 5

LOG_LINES = []

def log(msg):
    print(msg)
    LOG_LINES.append(msg)


# ── Raw data from SATYA DISTRIBUTORS report ───────────────────────────────────
# Each entry: customer name, phone (may be partial/multi), rep name, list of invoices
# Invoice: (date_str, product_name, qty, value)

REPORT = [
    {
        "customer": "AMRA RAM",
        "phone": "9705529596",
        "rep": "DR ANVESH",
        "invoices": [
            ("09/05/2026", "ZYORA MOUTHWASH 500ML",        1.0,   428.57),
            ("09/05/2026", "ZYORA MOUTHWASH 500ML",        2.0,   857.14),
        ],
    },
    {
        "customer": "BASAVATARAKAM INDO AMERICAN",
        "phone": "9966404696",
        "rep": None,
        "invoices": [
            ("30/05/2026", "EMWET SPRAY",                  10.0,  5065.70),
            ("20/05/2026", "NUNEXA 400GM",                 10.0,  9593.20),
            ("25/05/2026", "NUNEXA 400GM",                 10.0,  9593.20),
            ("30/05/2026", "ONCODOL 50 TAB",               38.0,  1900.00),
            ("19/05/2026", "XENOCAINE VISCOUS",            20.0,  2500.00),
            ("09/05/2026", "XEROWET MD",                   95.0,  25387.80),
            ("18/05/2026", "XEROWET MD",                   30.0,  8017.20),
            ("30/05/2026", "ZOLVERA LOTION 150ML",         20.0,  7240.00),
        ],
    },
    {
        "customer": "CHINA LAXMAIAH",
        "phone": "9985386313",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("21/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3333.33),
            ("21/05/2026", "LYCOTURM SYRUP 200ML",         1.0,   1714.28),
        ],
    },
    {
        "customer": "CONTINENTAL HOSPITALS",
        "phone": "7288889911",
        "rep": None,
        "invoices": [
            ("12/05/2026", "EMWET SPRAY",                  10.0,  4160.00),
        ],
    },
    {
        "customer": "D MANJULA",
        "phone": "7675056842",
        "rep": "DR SARATH CHANDRA G",
        "invoices": [
            ("30/05/2026", "XENOCAINE VISCOUS",            3.0,   771.42),
        ],
    },
    {
        "customer": "DR A RAJYALAKSHMI",
        "phone": "9490039891",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("07/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3809.52),
            ("07/05/2026", "LYCOTURM SYRUP 200ML",         1.0,   1714.29),
            ("07/05/2026", "NUTRIA CAPSULES",               3.0,   476.13),
            ("07/05/2026", "ZOLVERA LOTION 150ML",         1.0,   593.22),
        ],
    },
    {
        "customer": "DR DARWIN",
        "phone": "9441996257",
        "rep": "DR ANVESH",
        "invoices": [
            ("02/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3619.05),
            ("02/05/2026", "NUNEXA 400GM",                 1.0,   1619.05),
            ("02/05/2026", "NUTRIA CAPSULES",               3.0,   476.19),
        ],
    },
    {
        "customer": "DR SANKALPA NAIDU",
        "phone": "9959914308",
        "rep": "DR VIDYA SAGAR",
        "invoices": [
            ("12/05/2026", "REFILAC CAP 10S",              10.0,  2200.00),
            ("30/05/2026", "REFILAC CAP 10S",              20.0,  4400.00),
        ],
    },
    {
        "customer": "DURGA BAI DESHMUKH HOSPITAL",
        "phone": None,
        "rep": None,
        "invoices": [
            ("22/05/2026", "CAXIMEG ORAL SUSP 60ML",       10.0,  9062.50),
        ],
    },
    {
        "customer": "DURGABAI DESHMUKH HOSPITAL",
        "phone": "9502050103",
        "rep": "COUNTER SALES",
        "invoices": [
            ("04/05/2026", "CAXIMEG ORAL SUSP 60ML",       10.0,  9066.70),
            ("18/05/2026", "CAXIMEG ORAL SUSP 60ML",       10.0,  9066.70),
            ("30/05/2026", "CAXIMEG ORAL SUSP 60ML",       11.0,  9973.37),
            ("19/05/2026", "LYCOTURM SYRUP 200ML",         2.0,   2922.20),
        ],
    },
    {
        "customer": "DWARAKA MEDICAL DISTRIBUTORS",
        "phone": "9848626142",
        "rep": None,
        "invoices": [
            ("16/05/2026", "AMTRIOS SOFTGEL CAP 30",       3.0,   8850.00),
            ("29/05/2026", "AMTRIOS SOFTGEL CAP 30",       6.0,   17700.00),
            ("16/05/2026", "CAXIMEG ORAL SUSP 60ML",       15.0,  11250.00),
            ("04/05/2026", "LYCOTURM SYRUP 200ML",         2.0,   2923.72),
            ("04/05/2026", "LYCOTURM SYRUP 200ML",         3.0,   4385.58),
            ("11/05/2026", "LYCOTURM SYRUP 200ML",         5.0,   7309.30),
            ("16/05/2026", "LYCOTURM SYRUP 200ML",         6.0,   8771.16),
            ("29/05/2026", "LYCOTURM SYRUP 200ML",         5.0,   7309.30),
            ("12/05/2026", "NUTRIA CAPSULES",               30.0,  3177.90),
            ("29/05/2026", "NUTRIA CAPSULES",               10.0,  1059.30),
            ("29/05/2026", "NUTRIA CAPSULES",               40.0,  4237.20),
            ("16/05/2026", "REFILAC CAP 10S",              12.0,  2564.52),
            ("26/05/2026", "XENOCAINE VISCOUS",            10.0,  1928.60),
            ("16/05/2026", "XEROWET MD",                   5.0,   1250.00),
            ("29/05/2026", "ZOLVERA LOTION 150ML",         10.0,  4406.80),
        ],
    },
    {
        "customer": "GADDIPATI SAI RATNA",
        "phone": "7204020304",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("19/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3809.14),
            ("19/05/2026", "NUTRIA CAPSULES",               3.0,   476.10),
        ],
    },
    {
        "customer": "GANGA PHARMA DISTRIBUTORS",
        "phone": "9848000000",   # phone in PDF cut off; partial
        "rep": None,
        "invoices": [
            ("05/05/2026", "AMTRIOS SOFTGEL CAP 30",       2.0,   5932.20),
            ("21/05/2026", "AMTRIOS SOFTGEL CAP 30",       3.0,   8898.30),
            ("13/05/2026", "ZOLVERA LOTION 150ML",         5.0,   2620.30),
        ],
    },
    {
        "customer": "HYDERABAD INSTITUTE OF ONCOLOGY",
        "phone": "9951674903",
        "rep": None,
        "invoices": [
            ("04/05/2026", "AMTRIOS SOFTGEL CAP 30",       5.0,   9000.00),
            ("12/05/2026", "AMTRIOS SOFTGEL CAP 30",       10.0,  18000.00),
        ],
    },
    {
        "customer": "JANGAIAH",
        "phone": "7731923570",
        "rep": None,
        "invoices": [
            ("12/05/2026", "ZOLVERA LOTION 150ML",         1.0,   576.27),
        ],
    },
    {
        "customer": "JAYA SURGICAL AND PHARMA",
        "phone": "9951674903",   # PDF shows 04024542643; using numeric part
        "rep": None,
        "invoices": [
            ("29/05/2026", "NUNEXA 400GM",                 20.0,  27800.00),
            ("29/05/2026", "XENOCAINE VISCOUS",            20.0,  2924.00),
        ],
    },
    {
        "customer": "K RAMREDDY",
        "phone": "9000107298",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("05/05/2026", "LYCOTURM SYRUP 200ML",         1.0,   1714.29),
        ],
    },
    {
        "customer": "LAKSHMI",
        "phone": "9849926202",
        "rep": "DR SHARATH JAKKA",
        "invoices": [
            ("18/05/2026", "CAXIMEG ORAL SUSP 60ML",       1.0,   3809.52),
        ],
    },
    {
        "customer": "MEDICARE GALAXY LLP",
        "phone": "9290865979",
        "rep": None,
        "invoices": [
            ("22/05/2026", "AMTRIOS SOFTGEL CAP 30",       6.0,   16434.00),
        ],
    },
    {
        "customer": "MEDIHAUXE PHARMACEUTICALS",
        "phone": "9040485855",
        "rep": None,
        "invoices": [
            ("21/05/2026", "HEXAMUNE TABLETS",             50.0,  4900.00),
        ],
    },
    {
        "customer": "NATIONAL PHARMACY",
        "phone": "9807845845",
        "rep": "COUNTER SALES",
        "invoices": [
            ("05/05/2026", "CAXIMEG ORAL SUSP 60ML",       6.0,   5282.16),
            ("13/05/2026", "CAXIMEG ORAL SUSP 60ML",       2.0,   1760.72),
            ("13/05/2026", "CAXIMEG ORAL SUSP 60ML",       4.0,   3521.44),
            ("05/05/2026", "IMUNEXA CAPS",                 30.0,  7102.80),
            ("13/05/2026", "LYCOTURM SYRUP 200ML",         2.0,   2838.70),
            ("26/05/2026", "NUNEXA 400GM",                 2.0,   2869.84),
            ("13/05/2026", "NUTRIA CAPSULES",               40.0,  4794.00),
            ("30/05/2026", "NUTRIA CAPSULES",               30.0,  3595.50),
            ("13/05/2026", "ONCODOL 50 TAB",               20.0,  2367.80),
            ("05/05/2026", "REFILAC CAP 10S",              20.0,  8827.20),
            ("13/05/2026", "XENOCAINE VISCOUS",            5.0,   1092.85),
            ("13/05/2026", "XENOCAINE VISCOUS",            15.0,  3278.55),
            ("15/05/2026", "XENOCAINE VISCOUS",            30.0,  6557.10),
            ("05/05/2026", "ZOLVERA LOTION 150ML",         2.0,   950.84),
            ("05/05/2026", "ZYORA MOUTHWASH 500ML",        15.0,  5008.95),
        ],
    },
    {
        "customer": "NEERAJA REDDY",
        "phone": "9848024594",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("22/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3809.28),
            ("09/05/2026", "LYCOTURM SYRUP 200ML",         1.0,   1714.29),
            ("22/05/2026", "LYCOTURM SYRUP 200ML",         1.0,   1714.29),
            ("22/05/2026", "NUTRIA CAPSULES",               3.0,   476.04),
            ("22/05/2026", "ZOLVERA LOTION 150ML",         1.0,   666.66),
        ],
    },
    {
        "customer": "P KOTESHWARAMMA",
        "phone": "8341920259",
        "rep": None,
        "invoices": [
            ("08/05/2026", "REFILAC CAP 10S",              2.0,   500.00),
        ],
    },
    {
        "customer": "P VENKATAIAH",
        "phone": "9985014719",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("30/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3809.52),
            ("30/05/2026", "LYCOTURM SYRUP 200ML",         1.0,   1714.29),
            ("30/05/2026", "NUNEXA 400GM",                 1.0,   1688.14),
            ("30/05/2026", "NUTRIA CAPSULES",               5.0,   792.85),
        ],
    },
    {
        "customer": "PRASAD MEHTA",
        "phone": "9620037860",
        "rep": "DR S C MOULI",
        "invoices": [
            ("15/05/2026", "REFILAC CAP 10S",              6.0,   1508.52),
        ],
    },
    {
        "customer": "PURUSHOTTAM",
        "phone": "9347564857",
        "rep": "DR AVINASH BONDA",
        "invoices": [
            ("12/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3809.52),
            ("12/05/2026", "NUTRIA CAPSULES",               3.0,   476.19),
        ],
    },
    {
        "customer": "RAJANNA",
        "phone": "8919263999",
        "rep": "DR ANVESH",
        "invoices": [
            ("11/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3619.05),
            ("11/05/2026", "ZOLVERA LOTION 150ML",         1.0,   593.22),
        ],
    },
    {
        "customer": "RAMA MURTHY",
        "phone": "8978362441",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("16/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3809.52),
            ("16/05/2026", "LYCOTURM SYRUP 200ML",         1.0,   1714.29),
            ("16/05/2026", "NUTRIA CAPSULES",               2.0,   342.86),
        ],
    },
    {
        "customer": "RENOVA PHARMACY",
        "phone": "9705243321",
        "rep": "COUNTER SALES",
        "invoices": [
            ("07/05/2026", "EMWET SPRAY",                  1.0,   475.00),
        ],
    },
    {
        "customer": "RENOVA SOUMYA PHARMACY",
        "phone": "9908252963",
        "rep": "COUNTER SALES",
        "invoices": [
            ("23/05/2026", "EMWET SPRAY",                  2.0,   820.00),
            ("05/05/2026", "LYCOTURM SYRUP 200ML",         9.0,   11835.00),
            ("23/05/2026", "NUNEXA 400GM",                 2.0,   2624.00),
        ],
    },
    {
        "customer": "SACHIN ASTHAGE",
        "phone": "9373075845",
        "rep": "DR SARATH CHANDRA G",
        "invoices": [
            ("12/05/2026", "ZYORA MOUTHWASH 500ML",        2.0,   761.90),
        ],
    },
    {
        "customer": "SAVITRI",
        "phone": "9603064002",
        "rep": "DR ANVESH",
        "invoices": [
            ("09/05/2026", "AMTRIOS SOFTGEL CAP 30",       1.0,   3619.04),
            ("09/05/2026", "NUTRIA CAPSULES",               3.0,   476.19),
        ],
    },
    {
        "customer": "SHABANA",
        "phone": "9640875486",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("25/05/2026", "NUTRIA CAPSULES",               3.0,   571.41),
        ],
    },
    {
        "customer": "SHABANA BEGUM",
        "phone": "9963052471",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("04/05/2026", "NUTRIA CAPSULES",               2.0,   317.42),
        ],
    },
    {
        "customer": "SHOBHA",
        "phone": "9985100900",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("22/05/2026", "LYCOTURM SYRUP 200ML",         1.0,   1714.80),
            ("22/05/2026", "NUTRIA CAPSULES",               6.0,   952.20),
        ],
    },
    {
        "customer": "SRI SAI ASHIRWAD ENTERPRISES",
        "phone": "9959879545",
        "rep": "COUNTER SALES",
        "invoices": [
            ("25/05/2026", "NUNEXA 400GM",                 10.0,  13294.10),
            ("25/05/2026", "NUTAMINE SACHETS",             10.0,  1098.00),
        ],
    },
    {
        "customer": "SYED WAHEED",
        "phone": "9885866448",
        "rep": "DR ZOHA",
        "invoices": [
            ("08/05/2026", "CAXIMEG ORAL SUSP 60ML",       1.0,   1038.09),
        ],
    },
    {
        "customer": "VARSHA ARORA",
        "phone": "7984196410",
        "rep": "DR GANGADHAR",
        "invoices": [
            ("02/05/2026", "LYCOTURM SYRUP 200ML",         1.0,   1714.29),
        ],
    },
    {
        "customer": "VIJAY",
        "phone": "9640444431",
        "rep": "DR ARMURGAN",
        "invoices": [
            ("25/05/2026", "EMWET SPRAY",                  4.0,   2933.32),
            ("25/05/2026", "ZOLVERA LOTION 150ML",         1.0,   559.32),
            ("25/05/2026", "ZYORA MOUTHWASH 500ML",        1.0,   388.57),
        ],
    },
    {
        "customer": "ZAMRUD BEGUM",
        "phone": "9849051017",
        "rep": "DR SENTHIL RAJAPPA",
        "invoices": [
            ("16/05/2026", "CAXIMEG ORAL SUSP 60ML",       1.0,   3428.57),
        ],
    },
]


# ── Product name normalisation map ────────────────────────────────────────────
# Keys: name variants found in distributor report
# Values: canonical product name to use in DB (or None = skip import)
PRODUCT_ALIASES = {
    "ZYORA MOUTHWASH 500ML":    "ZYORA MOUTHWASH 500ML",
    "EMWET SPRAY":              "EMWET SPRAY",
    "NUNEXA 400GM":             "NUNEXA 400GM",
    "ONCODOL 50 TAB":           "ONCODOL 50 TAB",
    "XENOCAINE VISCOUS":        "XENOCAINE VISCOUS",
    "XEROWET MD":               "XEROWET MD",
    "ZOLVERA LOTION 150ML":     "ZOLVERA LOTION 150ML",
    "AMTRIOS SOFTGEL CAP 30":   "AMTRIOS SOFTGEL CAP 30",
    "LYCOTURM SYRUP 200ML":     "LYCOTURM SYRUP 200ML",
    "NUTRIA CAPSULES":           "NUTRIA CAPSULES 1*10S",
    "CAXIMEG ORAL SUSP 60ML":   "CAXIMEG ORAL SUSP 60ML",
    "REFILAC CAP 10S":          "REFILAC CAP 10S",
    "HEXAMUNE TABLETS":         "HEXAMUNE TABLETS",
    "IMUNEXA CAPS":             "IMUNEXA CAPS 10S",
    "NUTAMINE SACHETS":         "NUTAMINE SACHETS",
}


# ── Helper: fuzzy name match ───────────────────────────────────────────────────
def similarity(a: str, b: str) -> float:
    return SequenceMatcher(None, a.lower(), b.lower()).ratio()


def find_doctor_by_phone(phone: str):
    if not phone:
        return None
    # Clean phone — keep only digits
    digits = re.sub(r'\D', '', phone)
    # Try last 10 digits
    last10 = digits[-10:] if len(digits) >= 10 else digits
    all_docs = db.query(Doctor).filter(Doctor.is_active == True).all()
    for doc in all_docs:
        if not doc.phone:
            continue
        doc_digits = re.sub(r'\D', '', doc.phone)[-10:]
        if doc_digits == last10:
            return doc
    return None


def find_doctor_by_name(name: str):
    all_docs = db.query(Doctor).filter(Doctor.is_active == True).all()
    best, best_score = None, 0.0
    for doc in all_docs:
        s = similarity(name, doc.name or "")
        if s > best_score:
            best_score = s
            best = doc
    return best if best_score >= 0.7 else None


def find_or_create_product(raw_name: str):
    canonical = PRODUCT_ALIASES.get(raw_name.upper().strip(), raw_name.strip())
    # Try exact match
    prod = db.query(Product).filter(Product.name.ilike(canonical)).first()
    if prod:
        return prod
    # Try partial match
    all_prods = db.query(Product).all()
    for p in all_prods:
        if similarity(canonical, p.name) >= 0.80:
            return p
    # Auto-create
    log(f"  [NEW PRODUCT] '{canonical}' not found in DB — creating with rate=0 (update manually)")
    prod = Product(name=canonical, pack_size=None, rate=0.0, is_active=True)
    db.add(prod)
    db.commit()
    db.refresh(prod)
    return prod


def find_user_by_rep_name(rep_name: str):
    if not rep_name or rep_name.upper() in ("COUNTER SALES", "DR.", ""):
        return None
    # Strip "DR " prefix for matching
    clean = re.sub(r'^DR\.?\s*', '', rep_name, flags=re.IGNORECASE).strip()
    all_users = db.query(User).filter(User.is_active == True).all()
    best, best_score = None, 0.0
    for u in all_users:
        # Match against full name or clean name
        for candidate in [u.name or "", (u.name or "").split()[-1]]:
            s = similarity(clean, candidate)
            if s > best_score:
                best_score = s
                best = u
    return best if best_score >= 0.65 else None


# ─────────────────────────────────────────────────────────────────────────────
# MAIN IMPORT
# ─────────────────────────────────────────────────────────────────────────────

def run_import():
    log("━" * 60)
    log(f"  Fortel CRM  ←  SATYA DISTRIBUTORS  |  May {YEAR}")
    log("━" * 60)
    log(f"  Source  : SATYA DISTRIBUTORS secondary sales report")
    log(f"  Period  : 01 May {YEAR} – 31 May {YEAR}")
    log(f"  Records : {len(REPORT)} customers")
    log("━" * 60)

    unmatched_customers = []
    unmatched_reps      = []
    inserted            = 0
    skipped             = 0
    total_value         = 0.0

    for entry in REPORT:
        cname  = entry["customer"]
        phone  = entry["phone"]
        rep    = entry["rep"]

        # ── Match doctor ─────────────────────────────────────────
        doctor = find_doctor_by_phone(phone)
        if not doctor:
            doctor = find_doctor_by_name(cname)
        if not doctor:
            log(f"\n  ✗ {cname} (ph: {phone or 'n/a'}) — not found in doctor database")
            unmatched_customers.append({"customer": cname, "phone": phone, "rep": rep})
            continue

        log(f"\n  {cname}")
        log(f"  → Matched to: {doctor.name}  (Rep: {rep or 'unassigned'})")

        # ── Match rep (user) ──────────────────────────────────────
        user = find_user_by_rep_name(rep)
        if not user:
            unmatched_reps.append({"customer": cname, "rep": rep})
            fallback_user_id = doctor.manager_id
            if fallback_user_id:
                log(f"  → Rep '{rep}' not matched — using doctor's manager as fallback")
        else:
            fallback_user_id = user.id

        if not fallback_user_id:
            log(f"  → No rep or manager found — skipping this customer")
            skipped += len(entry["invoices"])
            continue

        # ── Process each invoice line ─────────────────────────────
        # Group all invoices by product → monthly total (qty + value)
        # Distributor report is monthly, so we store one entry per doctor×product
        # with week=1 and source tag in remarks.
        monthly_totals = {}   # canonical_product_name → [total_qty, total_value]

        for (date_str, prod_raw, qty, value) in entry["invoices"]:
            canonical = PRODUCT_ALIASES.get(prod_raw.upper().strip(), prod_raw.strip())
            if canonical not in monthly_totals:
                monthly_totals[canonical] = [0.0, 0.0]
            monthly_totals[canonical][0] += qty
            monthly_totals[canonical][1] += value

        for canonical, (qty, value) in monthly_totals.items():
            product = find_or_create_product(canonical)

            # Check for existing monthly entry (week=1 = distributor monthly total)
            existing = db.query(SalesEntry).filter(
                SalesEntry.doctor_id    == doctor.id,
                SalesEntry.associate_id == fallback_user_id,
                SalesEntry.product_id   == product.id,
                SalesEntry.year         == YEAR,
                SalesEntry.month        == MONTH,
                SalesEntry.week         == 1,
            ).first()

            if existing:
                existing.quantity = qty      # overwrite with distributor figure
                existing.value    = value
                existing.remarks  = "SATYA DISTRIBUTORS — May 2026 (monthly total)"
                existing.is_approved = True
                db.commit()
                log(f"  ↻  {product.name}: {qty:.0f} units  ₹{value:,.2f}  (updated)")
                inserted += 1
                total_value += value
            else:
                entry_obj = SalesEntry(
                    doctor_id    = doctor.id,
                    associate_id = fallback_user_id,
                    product_id   = product.id,
                    year         = YEAR,
                    month        = MONTH,
                    week         = 1,
                    quantity     = qty,
                    value        = value,
                    remarks      = "SATYA DISTRIBUTORS — May 2026 (monthly total)",
                    is_approved  = True,
                    submitted_at = datetime.utcnow(),
                )
                db.add(entry_obj)
                db.commit()
                log(f"  ✓  {product.name}: {qty:.0f} units  ₹{value:,.2f}")
                inserted += 1
                total_value += value

    # ── Summary ───────────────────────────────────────────────────────────────
    log("\n" + "━" * 60)
    log("  IMPORT COMPLETE")
    log("━" * 60)
    log(f"  ✓ Sales entries saved   : {inserted}")
    log(f"  ✗ Entries skipped       : {skipped}")
    log(f"  Total value imported    : ₹{total_value:,.2f}")
    log(f"  Customers matched       : {len(REPORT) - len(unmatched_customers)} / {len(REPORT)}")
    log("")

    if unmatched_customers:
        log(f"  ⚠  {len(unmatched_customers)} customer(s) not found in your doctor database.")
        log("     Add them as doctors first, then re-run this script:")
        for u in unmatched_customers:
            phone_str = f"ph: {u['phone']}" if u["phone"] else "no phone"
            log(f"     • {u['customer']}  ({phone_str})  rep: {u['rep'] or 'unassigned'}")
        log("")

    if unmatched_reps:
        matched_set = set(u["rep"] for u in unmatched_reps if u["rep"])
        log(f"  ℹ  {len(matched_set)} rep name(s) from the report didn't match any user.")
        log("     Doctor's manager was used as fallback. Verify these:")
        for rep_name in sorted(matched_set):
            log(f"     • '{rep_name}'")

    # Write log file
    log_path = os.path.join(os.path.dirname(__file__), "satya_import_log.txt")
    with open(log_path, "w", encoding="utf-8") as f:
        f.write("\n".join(LOG_LINES))
    print(f"\nFull log written to: {log_path}")


if __name__ == "__main__":
    try:
        run_import()
    finally:
        db.close()
